resources:
  containers:
  - container: 'azure-powershell-core'
    image: 'azuresdk/azure-powershell-core'

pool: 'Hosted Ubuntu 1604'
# container: 'azure-powershell-core'

steps:
- task: AzureResourceGroupDeployment@2
  inputs:
    azureSubscription: 'ARM'
    type: 'Incremental'
    resourceGroupName: 'contosodev-ccd_customguestconfig'
    location: 'eastus2'
    csmFileLink: deploy.json
    csmParametersFileLink: deploy.parameters.json
    overrideParameters: '-adminUsername $(adminUsername) -adminPassword $(adminPassword)'
