resources:
  containers:
  - container: 'azure-powershell-core'
    image: 'azuresdk/azure-powershell-core'

pool: 'Hosted Ubuntu 1604'
container: 'azure-powershell-core'

variables:
  buildConfiguration: 'Release'

steps:
- script: |
    write-host 'hello, world'
  displayName: 'hello, world'
