variables:
- group: vmusers

pool: 'Hosted VS2017'

steps:
- task: AzurePowerShell@3
  displayName: 'Publish Azure Policy definition for DeployIfNotExists rule'
  inputs:
    azureSubscription: 'ARM'
    azurePowerShellVersion: 'latestVersion'
    scriptType: 'inlineScript'
    inline: |
      param(`$path)
      $definition = (Get-Content `$path | ConvertFrom-Json -AsHashtable).Values
      New-AzureRMPolicyDefinition @definition -verbose
    scriptArguments: '-path $(Build.SourcesDirectory)\customPolicyFiles\deployIfNotExists.json'
- task: AzureResourceGroupDeployment@2
  displayName: "Deploy virtual machine to Azure"
  inputs:
    azureSubscription: 'ARM'
    resourceGroupName: 'contosodev-ccd_customguestconfig'
    type: 'Complete'
    location: 'eastus2'
    csmFile: deploy.json
    overrideParameters: '-adminUsername $(adminUsername) -adminPassword $(adminPassword)'
