variables:
- group: vmusers

pool: 'Hosted VS2017'

steps:
- task: AzurePowerShell@3
  inputs:
    azureSubscription: 'ARM'
    azurePowerShellVersion: 'latestVersion'
    scriptType: 'inlineScript'
    inline: |
      $definition = (Get-Content {0} | ConvertFrom-Json -AsHashtable).Values
      New-AzureRMPolicyDefinition @definition -verbose
    scriptArguments: '$(Build.SourcesDirectory)\customPolicyFiles\deployIfNotExists.json'
- task: AzureResourceGroupDeployment@2
  inputs:
    azureSubscription: 'ARM'
    resourceGroupName: 'contosodev-ccd_customguestconfig'
    type: 'Complete'
    location: 'eastus2'
    csmFile: deploy.json
    overrideParameters: '-adminUsername $(adminUsername) -adminPassword $(adminPassword)'
