resources:
  containers:
  - container: 'azure-powershell-core'
    image: 'azuresdk/azure-powershell-core'

pool: 'Hosted Ubuntu 1604'
container: 'azure-powershell-core'

variables:
  buildConfiguration: 'Release'

- task: AzureResourceGroupDeployment@2
  inputs:
    azureSubscription: 'ARM'
    resourceGroupName: 'contosodev-ccd_customguestconfig'
    templateLocation: 'URL of the file'
    csmFileLink: '$(Build.Repository.LocalPath)/deploy.json'
    overrideParameters: '-adminUsername $(adminUsername) -adminPassword $(adminPassword)'
