resources:
  containers:
  - container: 'azure-powershell-core'
    image: 'azuresdk/azure-powershell-core'
 container: 'azure-powershell-core'

variables:
- group: vmusers

pool: 'Hosted Ubuntu 1604'

steps:
- script: |
    pwsh
    write-out 'hello, world'
- task: AzureResourceGroupDeployment@2
  inputs:
    azureSubscription: 'ARM'
    resourceGroupName: 'contosodev-ccd_customguestconfig'
    type: 'Complete'
    location: 'eastus2'
    csmFile: deploy.json
    overrideParameters: '-adminUsername $(adminUsername) -adminPassword $(adminPassword)'
