variables:
- group: vmusers

pool: 'Hosted VS2017'

steps:
- powershell: |
    ls 'c:\Program Files\PowerShell'
    Invoke-WebRequest -Uri 'https://github.com/PowerShell/PowerShell/releases/download/v6.2.0-preview.2/PowerShell-6.2.0-preview.2-win-x64.msi' -OutFile "$env:temp\PowerShell-6.2.0-preview.2-win-x64.msi"
    Unblock-File "$env:temp\PowerShell-6.2.0-preview.2-win-x64.msi"
    & "$env:temp\PowerShell-6.2.0-preview.2-win-x64.msi" -quiet
- task: AzurePowerShell@3
  displayName: 'Publish Azure Policy definition for DeployIfNotExists rule'
  inputs:
    azureSubscription: 'ARM'
    azurePowerShellVersion: 'latestVersion'
    scriptType: 'inlineScript'
    inline: |
      & 'C:\Program Files\PowerShell\6-preview\pwsh.exe' -command {write 'hello, world'}
      #$definition = (Get-Content "$(Build.SourcesDirectory)\customPolicyFiles\deployIfNotExists.json" | ConvertFrom-Json -AsHashtable).Values
      #New-AzureRMPolicyDefinition @definition -verbose
- task: AzureResourceGroupDeployment@2
  displayName: "Deploy virtual machine to Azure"
  inputs:
    azureSubscription: 'ARM'
    resourceGroupName: 'contosodev-ccd_customguestconfig'
    type: 'Complete'
    location: 'eastus2'
    csmFile: deploy.json
    overrideParameters: '-adminUsername $(adminUsername) -adminPassword $(adminPassword)'
