variables:
- group: vmusers

pool: 'Hosted VS2017'

steps:
- task: AzurePowerShell@3
  inputs:
    azureSubscription: 'ARM'
    scriptType: 'inlineScript'
    inline: |
      get-azurermresourcegroup -name 'contosodev-ccd_customguestconfig'
    #scriptArguments: # Optional
    #errorActionPreference: 'stop' # Optional. Options: stop, continue, silentlyContinue
    #failOnStandardError: false # Optional
- task: AzureResourceGroupDeployment@2
  inputs:
    azureSubscription: 'ARM'
    resourceGroupName: 'contosodev-ccd_customguestconfig'
    type: 'Complete'
    location: 'eastus2'
    csmFile: deploy.json
    overrideParameters: '-adminUsername $(adminUsername) -adminPassword $(adminPassword)'
