/*
@TargetNode='Localhost'
@GeneratedBy=AzurePolicyGuestConfiguration
@GenerationDate=11/26/2018 12:00:00
@GenerationHost=Host
*/

instance of MSFT_AccountPolicy as $MSFT_AccountPolicy1ref
{
ResourceID = "[AccountPolicy]PasswordPolicy";
 Enforce_password_history = 12;
 Maximum_Password_Age = 90;
 Minimum_Password_Age = 0;
 Minimum_Password_Length = 8;
 Password_must_meet_complexity_requirements = 'Enabled';
 Store_passwords_using_reversible_encryption = 'Disabled';
 SourceInfo = "::49::3::AccountPolicy";
 Name = "PasswordPolicy";
 ModuleName = "SecurityPolicyDsc";
 ModuleVersion = "2.4.0.0";

 ConfigurationName = "PasswordPolicy_v0.2";

};
instance of OMI_ConfigurationDocument


                    {
 Version="2.0.0";


                        MinimumCompatibleVersion = "1.0.0";


                        CompatibleVersionAdditionalProperties= {"Omi_BaseResource:ConfigurationName"};


                        Author="AzurePolicyGuestConfiguration";


                        GenerationDate="11/26/2018 12:00:00";


                        GenerationHost="Host";


                        Name="PasswordPolicy_v0.2";


                    };
